---
    - name: Install and Configure Database
      apt: name={{ item }} state=present
      with_items:
        - mariadb-server
        - mariadb-client
    - name: Start MariaDB server
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Create Application Database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
    - name: Create Datbase User
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
